// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAioAKaH0ZCzQoU0kk5y9PSPNuM2rxuNT0',
    appId: '1:422783082004:web:9ba73ee5e917c101c0d101',
    messagingSenderId: '422783082004',
    projectId: 'mizdah-ce042',
    authDomain: 'mizdah-ce042.firebaseapp.com',
    storageBucket: 'mizdah-ce042.firebasestorage.app',
    measurementId: 'G-75ED9YB9S6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCITrljOBuLucW8eJ81k6_eJgDRRc9XD1w',
    appId: '1:422783082004:android:66f66acc47b8cf3dc0d101',
    messagingSenderId: '422783082004',
    projectId: 'mizdah-ce042',
    storageBucket: 'mizdah-ce042.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEg_Xly0x_-h8CN0zxjjhxmSO321YjnW0',
    appId: '1:422783082004:ios:55b366a6db71c738c0d101',
    messagingSenderId: '422783082004',
    projectId: 'mizdah-ce042',
    storageBucket: 'mizdah-ce042.firebasestorage.app',
    iosBundleId: 'com.mizdah.mizdah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEg_Xly0x_-h8CN0zxjjhxmSO321YjnW0',
    appId: '1:422783082004:ios:55b366a6db71c738c0d101',
    messagingSenderId: '422783082004',
    projectId: 'mizdah-ce042',
    storageBucket: 'mizdah-ce042.firebasestorage.app',
    iosBundleId: 'com.mizdah.mizdah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAioAKaH0ZCzQoU0kk5y9PSPNuM2rxuNT0',
    appId: '1:422783082004:web:e69685d7255b0d8ec0d101',
    messagingSenderId: '422783082004',
    projectId: 'mizdah-ce042',
    authDomain: 'mizdah-ce042.firebaseapp.com',
    storageBucket: 'mizdah-ce042.firebasestorage.app',
    measurementId: 'G-HLXYVRLEGW',
  );
}
